

# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
    build:
      docker:
        - image: circleci/node:14.17.0-browsers
        - image: selenium/standalone-chrome
          environment:
            # Fix issue with selenium-server in containers.
            # See http://github.com/SeleniumHQ/docker-selenium/issues/871
            DBUS_SESSION_BUS_ADDRESS: /dev/null
      steps:
        - checkout
  
        - run: google-chrome --version
  
        - run:
            name: NPM Install
            command: |
              npm i
        - save_cache:
            key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
            paths:
              - "node_modules"
        - run:
            name: Run test
            command: npm test

        - store_test_results:
            path: ~/e2e/Result/
